### ISSUE TITLE
Decipher Adjacent Nodes

### ISSUE THREAD

**Issue by Averynder** [jaychenblue/scout-concordia#141]
This will require the dev to decide how the adjacent nodes will be read in from, either by applying one of the 2 following possibilities:
- Creating a new data file with a format of how to specify adjacent nodes
- creating a way of determining which nodes are adjacent (preferably by distance)

Requirements:
- [x] Issue #138 must be completed
- [x] Issue #139 must be completed
- [x] Issue #140 must be completed

Acceptance Criteria:
- [x] A text file with a list of all classrooms and their latitude and longitude coordinates. 
- [x] A list of edges can be created from either method
- [x] The list of edges can be inserted within a graph
- [x] The list of edges within the map can be retrieved

**Comment by vincentcerri** [comment]
Update: we can read in from a text file a list of LatLng for a specific floor. With this information, we can created Nodes using the points, which are then all turned into a graph for the floor. The edges between the nodes are calculated based on length in meters (can use this for finding path length later). Every node in the graph has an adjacency list which shows which nodes are next to it. 

To do: Finish creating the LatLng files for each of the floors. Very tedious process.

**Comment by vincentcerri** [comment]
update: Testing out breadth first search now that we hall all nodes for hall 8th floor 
![8.PNG](https://images.zenhubusercontent.com/5e2890685e668415cad9a0be/30db7722-a6cb-4193-9dac-f24b258965a7)

**Comment by Averynder** [comment]
After the following commit the previous path displayed is no longer viewed however upon testing it on a manually made graph it can be viewed that this indeed works.
![Use2](https://user-images.githubusercontent.com/36492119/77597388-181f1100-6ed5-11ea-8154-0c66cadc0ab2.png)
The Green Nodes represent nodes that were considered classrooms, the yellow was the path given and the red are regular nodes. Here is the results:
![pp](https://user-images.githubusercontent.com/36492119/77597456-4e5c9080-6ed5-11ea-89ff-5c10d83c7df6.png)

**Comment by Averynder** [comment]
Fixed path not displaying:
![Working Path](https://user-images.githubusercontent.com/36492119/77610176-5843bb00-6ef8-11ea-8c9b-ce388b74df65.png)
