### ISSUE TITLE
BY-45  As a developer, I need to test all user stories before merging them to master.

### ISSUE THREAD

**Issue by JenYn** [jaychenblue/scout-concordia#68]
As a developer, I need to manually test all pull requests and make sure that they pass the acceptance criteria before merging a branch onto master.

Requirements:
testing dependencies are successfully installed within the project (Espresso & Junit 5)
- [x] #13 has been completed
- [x] #6 has been completed
- [x] #14 has been completed
- [x] #15 has been completed
- [ ] #24 has been completed
- [ ] #81 has been completed
- [ ] #70 has been completed

Acceptance Tests:
- [ ] All tests can be run successfully without errors
- [ ] The tests perform the required clicks / actions to verify the feature
- [ ] None of the tests leave resources modified ex: data files

Accomplishments:
- Regression tests have been created thus allowing the team to develop further with no longer a need to manually verify if all the features previously developed are still working.

**Comment by JenYn** [comment]
Process of merging:
- [ ] Commit changes to a branch
- [ ] Create a pull request on the branch when it is done being implemented
- [ ] Have at least two people review the branch and test it
- [ ] Leave a comment/approve/disapprove the pull request after testing it manually 
- [ ] If two people approve the pull request, it can be merged

**Comment by JenYn** [comment]
This issue is constantly ongoing, thus we will only close it at the end of sprint 2.
